name: deployment workflows
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 118.70.181.146
          username: hoangnv
          key: ${{secrets.TEST_GITHUB_ACTION}}
          passphrase: ${{secrets.PASSWORD}}
          port: 6789
          script: |
            cd /media/2tb/Hoang/multitask/code/ssd
            source /home/ailab/anaconda3/bin/activate
            conda activate multitask
            sh train.sh
            
            
