name: deployment workflows
on:
  push:
    branches: [master]

jobs:
  job_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: testing server ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: 118.70.181.146
          user: hoangnv
          key: ${{secrets.TEST_GITHUB_ACTION}}
          port: 6789
          script: |
            cd /home/hoangnv
            ls -la
            mkdir test
            
